### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by Dradon7** [Stereowalker/Burden-Of-Time#1]
Using forge 36.1.4, Minecraft 1.16.5, Burden of Time 0.0.2, and UnionLib 3.3.2 in a completely new instance, Minecraft crashes on startup.

**How to reproduce:**
Create a new instance of minecraft. Download and install the latest forge. Install both Burden of Time 0.0.2 and UnionLib 3.3.2. Run the instance.

You don't have a issue template, so I'm not sure what else I need to include. Let me know if you need more information.

**Comment by Stereowalker** [comment]
Update BOT to 0.0.4
