### ISSUE TITLE
Move conversions list to config

### ISSUE THREAD

**Issue by SneakyAlba** [Stereowalker/Burden-Of-Time#3]
A suggestion that might take some workload off of you in future: allow users to include new block conversions in the config file rather than hardcoding them. This opens the door for modpacks to include blocks from unsupported mods or potentially enable per-block ageing times.

**Comment by Stereowalker** [comment]
Due to the intricate nature of the conversions, it isn't possible to add them via config, but unless you're okay with datapacks I can make it modifiable with datapacks
